#include <iostream>
using namespace std;

int main()
{
int money,partner_age;
cout<<"enter money you have"<<endl;
cin>>money;

if(money>=1000)
{
	cout<<"enter partner_age:";
	cin>>partner_age;
	if(partner_age>21)
	{
		cout<<"lets have wine";
	}
	else
	{
		cout<<"lets have coffee";
	}
}
	else{
		cout<<"lets have coffee in Mombasa";
	}
	
	{
		if(money>500)
		{
			cout<<"coffee in nairobi";
		}
	}
	{
	{
		cout<<"coffee in normal shop";
	}}
	cout<<"lets go home";
	return 0;
}